slug: guotou
packages:
- com.hexin.plat.android.GuotouSecurity
verified_versions:
- version: 10.5.04
  verified_at: '2026-08-26'
compatibility:
  min: V10.5.4
  max_exclusive: V10.5.5
test_accounts: 
- {alias: pt, type: 普通, mask: "***0086"}
environment: env.yaml
profile: profile.yaml
prerequisites: prerequisites.yaml
aliases:
- 国投证券
- 安信证券
- 国投
